export const ACTOR_TYPE = {
  EMPLOYEE: 'employee',
  CUSTOMER: 'customer',
};

export const DELIVERY_STATUS = {
  ORDER_CREATED: 'created',
  PROCESSING: 'processing',
  SHIPPED: 'shipped',
  DELIVERED: 'delivered',
  CANCELLED: 'cancelled',
};

export const ALLOWED_STATUS_TRANSITIONS = {
  [DELIVERY_STATUS.ORDER_CREATED]: [DELIVERY_STATUS.PROCESSING],
  [DELIVERY_STATUS.PROCESSING]: [
    DELIVERY_STATUS.SHIPPED,
    DELIVERY_STATUS.CANCELLED,
  ],
  [DELIVERY_STATUS.SHIPPED]: [
    DELIVERY_STATUS.PROCESSING,
    DELIVERY_STATUS.DELIVERED,
  ],
  [DELIVERY_STATUS.DELIVERED]: [],
  [DELIVERY_STATUS.CANCELLED]: [],
};

export const DELIVERY_STATUS_ENUM = Object.values(DELIVERY_STATUS);
export const ACTOR_TYPE_ENUM = Object.values(ACTOR_TYPE);
