export enum ValidationMessage {
  InvalidEmail = 'invalidEmail',
  MustBeGreaterEqual = 'mustBeGreaterEqual',
  PasswordDoNotMatch = 'passwordDoNotMatch',
  PasswordLowercase = 'passwordLowercase',
  PasswordMinLength = 'passwordMinLength',
  PasswordNumber = 'passwordNumber',
  PasswordSymbol = 'passwordSymbol',
  PasswordUppercase = 'passwordUppercase',
  PleaseEnter = 'pleaseEnter',
  PleaseEnterName = 'pleaseEnterName',
  PleaseEnterPassword = 'pleaseEnterPassword',
  PleaseEnterValidEmail = 'pleaseEnterValidEmail',
}

export enum PopupRole {
  Alert = 'alert',
  Status = 'status',
}

export enum KeyCode {
  Alt = 'AltLeft',
  ArrowDown = 'ArrowDown',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight',
  ArrowUp = 'ArrowUp',
  End = 'End',
  Enter = 'Enter',
  Esc = 'Escape',
  Home = 'Home',
  Shift = 'ShiftLeft',
  Space = 'Space',
  Tab = 'Tab',
}

export enum SizeVariant {
  Lg = 'lg',
  Md = 'md',
  Sm = 'sm',
}

export enum BtnVariant {
  Ghost = 'ghost',
  Link = 'link',
  Primary = 'primary',
  Secondary = 'secondary',
}

export enum IconName {
  Account = 'account',
  Add = 'add',
  Admin = 'admin',
  ArrowDown = 'arrowDown',
  ArrowUp = 'arrowUp',
  Auth = 'auth',
  Categories = 'categories',
  ChevronDown = 'chevronDown',
  ChevronLeft = 'chevronLeft',
  ChevronRight = 'chevronRight',
  ChevronsLeft = 'chevronsLeft',
  ChevronsRight = 'chevronsRight',
  ChevronUp = 'chevronUp',
  Close = 'close',
  Dashboard = 'dashboard',
  Edit = 'edit',
  Error = 'error',
  Eye = 'eye',
  EyeOff = 'eyeOff',
  Filter = 'filter',
  Grid = 'grid',
  GridLarge = 'gridLarge',
  GridSmall = 'gridSmall',
  Info = 'info',
  Language = 'language',
  Login = 'login',
  Logo = 'logo',
  Logout = 'logout',
  More = 'more',
  Orders = 'orders',
  Products = 'products',
  Search = 'search',
  ShoppingBack = 'shoppingBack',
  Subtract = 'subtract',
  Success = 'success',
  Trash = 'trach',
  Undo = 'undo',
  User = 'user',
  Users = 'users',
  Warning = 'warning',
}
