export enum ValidationMessage {
  BrandRequired = 'brandRequired',
  CategoryRequired = 'categoryRequired',
  ColorRequired = 'colorRequired',
  ImageRequired = 'imageRequired',
  MaterialRequired = 'materialRequired',
  PasswordDoNotMatch = 'passwordDoNotMatch',
  PasswordLowercase = 'passwordLowercase',
  PasswordMinLength = 'passwordMinLength',
  PasswordNumber = 'passwordNumber',
  PasswordSymbol = 'passwordSymbol',
  PasswordUppercase = 'passwordUppercase',
  PleaseEnter = 'pleaseEnter',
  PleaseEnterCategoryName = 'pleaseEnterCategoryName',
  PleaseEnterEmail = 'noEmail',
  PleaseEnterName = 'pleaseEnterName',
  PleaseEnterPassword = 'pleaseEnterPassword',
  PleaseEnterSubCategoryName = 'pleaseEnterSubCategoryName',
  PleaseEnterTranslationKey = 'pleaseEnterTranslationKey',
  PleaseEnterValidEmail = 'pleaseEnterValidEmail',
  PleaseSelectParentCategory = 'pleaseSelectParentCategory',
  PriceRequired = 'priceRequired',
  ProductDescriptionRequired = 'productDescriptionRequired',
  ProductNameRequired = 'productNameRequired',
  SizeRequired = 'sizeRequired',
  UnknownError = 'unknownError',
}

export enum PopupRole {
  Alert = 'alert',
  Status = 'status',
}

export enum KeyCode {
  Alt = 'AltLeft',
  ArrowDown = 'ArrowDown',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight',
  ArrowUp = 'ArrowUp',
  End = 'End',
  Enter = 'Enter',
  Esc = 'Escape',
  Home = 'Home',
  Shift = 'ShiftLeft',
  Space = 'Space',
  Tab = 'Tab',
}

export enum SizeVariant {
  Lg = 'lg',
  Md = 'md',
  Sm = 'sm',
}

export enum BtnVariant {
  Danger = 'danger',
  Default = 'default',
  Ghost = 'ghost',
  Primary = 'primary',
  Secondary = 'secondary',
}

export enum IconName {
  Account = 'account',
  Add = 'add',
  Admin = 'admin',
  ArrowDown = 'arrowDown',
  ArrowUp = 'arrowUp',
  Auth = 'auth',
  Calendar = 'calendar',
  Categories = 'categories',
  Check = 'check',
  ChevronLeft = 'chevronLeft',
  ChevronRight = 'chevronRight',
  CircelChevronRight = 'circelChevronRight',
  Close = 'close',
  Dashboard = 'dashboard',
  Dublicate = 'dublicate',
  Edit = 'edit',
  Error = 'error',
  Eye = 'eye',
  EyeOff = 'eyeOff',
  Filter = 'filter',
  Grid = 'grid',
  GridLarge = 'gridLarge',
  GridSmall = 'gridSmall',
  Heart = 'heart',
  Image = 'image',
  Info = 'info',
  Language = 'language',
  LayoutGrid = 'layoutGrid',
  LayoutList = 'layoutList',
  Login = 'login',
  Logo = 'logo',
  Logout = 'logout',
  MenuDotsHorizontal = 'menuDotsHorizontal',
  Orders = 'orders',
  Products = 'products',
  Search = 'search',
  ShoppingBag = 'shoppingBag',
  SubCategories = 'subCategories',
  Subtract = 'subtract',
  Success = 'success',
  Trash = 'trach',
  Undo = 'undo',
  Upload = 'upload',
  User = 'user',
  Users = 'users',
  Warning = 'warning',
}
