import { ButtonHTMLAttributes } from 'react';

export enum ValidationMessage {
  BrandRequired = 'brandRequired',
  CardHasExpired = 'cardHasExpired',
  CardNumberMustContainExactly16Digits = 'cardNumberMustContainExactly16Digits',
  CategoryRequired = 'categoryRequired',
  ColorRequired = 'colorRequired',
  discountRange = 'discountRange',
  ImageRequired = 'imageRequired',
  InvalidExpiryDateFormat = 'invalidExpiryDateFormat',
  MaterialRequired = 'materialRequired',
  nothingWasUpdated = 'nothingWasUpdated',
  PasswordDoNotMatch = 'passwordDoNotMatch',
  PasswordLowercase = 'passwordLowercase',
  PasswordMinLength = 'passwordMinLength',
  PasswordNumber = 'passwordNumber',
  PasswordSymbol = 'passwordSymbol',
  PasswordUppercase = 'passwordUppercase',
  PayPalPasswordMustContainAtLeast6Characters = 'payPalPasswordMustContainAtLeast6Characters',
  PhoneNumberMustContainExactly8Digits = 'phoneNumberMustContainExactly8Digits',
  PleaseEnter = 'pleaseEnter',
  PleaseEnterCardholderName = 'pleaseEnterCardholderName',
  PleaseEnterCategoryName = 'pleaseEnterCategoryName',
  PleaseEnterCity = 'pleaseEnterCity',
  PleaseEnterDiscountCode = 'pleaseEnterDiscountCode',
  PleaseEnterEmail = 'noEmail',
  PleaseEnterName = 'pleaseEnterName',
  PleaseEnterPassword = 'pleaseEnterPassword',
  PleaseEnterStreet = 'pleaseEnterStreet',
  PleaseEnterSubCategoryName = 'pleaseEnterSubCategoryName',
  PleaseEnterTranslationKey = 'pleaseEnterTranslationKey',
  PleaseEnterValidEmail = 'pleaseEnterValidEmail',
  PleaseEnterZipcode = 'pleaseEnterZipcode',
  PleaseSelectParentCategory = 'pleaseSelectParentCategory',
  PriceRequired = 'priceRequired',
  ProductDescriptionRequired = 'productDescriptionRequired',
  ProductNameRequired = 'productNameRequired',
  SecurityCodeMustContain3Or4Digits = 'securityCodeMustContain3Or4Digits',
  SizeRequired = 'sizeRequired',
  UnknownError = 'unknownError',
}

export enum PopupRole {
  Alert = 'alert',
  Status = 'status',
}

export enum KeyCode {
  Alt = 'AltLeft',
  ArrowDown = 'ArrowDown',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight',
  ArrowUp = 'ArrowUp',
  End = 'End',
  Enter = 'Enter',
  Esc = 'Escape',
  Home = 'Home',
  Shift = 'ShiftLeft',
  Space = 'Space',
  Tab = 'Tab',
}

export enum SizeVariant {
  Lg = 'lg',
  Md = 'md',
  Sm = 'sm',
}

export enum BtnVariant {
  Danger = 'danger',
  Default = 'default',
  Ghost = 'ghost',
  Primary = 'primary',
  Secondary = 'secondary',
}

export type BtnType = ButtonHTMLAttributes<HTMLButtonElement>['type'];

export enum IconName {
  Account = 'account',
  Add = 'add',
  Admin = 'admin',
  ArrowDown = 'arrowDown',
  ArrowUp = 'arrowUp',
  Auth = 'auth',
  Calendar = 'calendar',
  Categories = 'categories',
  Check = 'check',
  ChevronDown = 'chevronDown',
  ChevronLeft = 'chevronLeft',
  ChevronRight = 'chevronRight',
  ChevronsLeft = 'chevronsLeft',
  ChevronsRight = 'chevronsRight',
  CircleChevronRight = 'circleChevronRight',
  Close = 'close',
  Dashboard = 'dashboard',
  Dublicate = 'dublicate',
  Error = 'error',
  Eye = 'eye',
  EyeOff = 'eyeOff',
  Filter = 'filter',
  Grid = 'grid',
  GridLarge = 'gridLarge',
  GridSmall = 'gridSmall',
  HalfStar = 'halfStar',
  Heart = 'heart',
  Image = 'image',
  Info = 'info',
  Kid = 'kid',
  Language = 'language',
  LayoutGrid = 'layoutGrid',
  LayoutList = 'layoutList',
  Login = 'login',
  Logo = 'logo',
  Logout = 'logout',
  Man = 'man',
  Mastercard = 'mastercard',
  MenuDotsHorizontal = 'menuDotsHorizontal',
  MobilePay = 'mobilePay',
  More = 'more',
  Orders = 'orders',
  PayPal = 'payPal',
  Pencil = 'pencil',
  Products = 'products',
  Search = 'search',
  ShoppingBag = 'shoppingBag',
  Star = 'star',
  SubCategories = 'subCategories',
  Subtract = 'subtract',
  Success = 'success',
  Trash = 'trach',
  Undo = 'undo',
  Upload = 'upload',
  User = 'user',
  Users = 'users',
  Visa = 'visa',
  Warning = 'warning',
  Woman = 'woman',
}
