import { useLanguage } from '../../features/language/useLanguage';
import VisuallyHidden from '../VisuallyHidden';

const SizeGuide = () => {
  const { language } = useLanguage();
  return (
    <section>
      <h2>{language.sizeGuideIntro}</h2>
      <p>{language.sizeGuideNote}</p>
      <table className="size-guide">
        <VisuallyHidden as="caption">
          {language.bodyMeasurements}
        </VisuallyHidden>
        <thead>
          <tr>
            <th scope="col">
              <span>EU</span>
            </th>
            <th scope="col">
              <span>INT</span>
            </th>
            <th scope="col">
              <span>{language.chest}</span>
            </th>
            <th scope="col">
              <span>{language.waist}</span>
            </th>
            <th scope="col">
              <span>{language.hips}</span>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>32</span>
            </td>
            <td>
              <span>XXS</span>
            </td>
            <td>
              <span>76</span>
            </td>
            <td>
              <span>63</span>
            </td>
            <td>
              <span>85</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>34</span>
            </td>
            <td>
              <span>XS</span>
            </td>
            <td>
              <span>80</span>
            </td>
            <td>
              <span>66</span>
            </td>
            <td>
              <span>89</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>36</span>
            </td>
            <td>
              <span>S</span>
            </td>
            <td>
              <span>84</span>
            </td>
            <td>
              <span>69</span>
            </td>
            <td>
              <span>93</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>38</span>
            </td>
            <td>
              <span>M</span>
            </td>
            <td>
              <span>88</span>
            </td>
            <td>
              <span>72</span>
            </td>
            <td>
              <span>97</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>40</span>
            </td>
            <td>
              <span>L</span>
            </td>
            <td>
              <span>92</span>
            </td>
            <td>
              <span>76</span>
            </td>
            <td>
              <span>100</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>42</span>
            </td>
            <td>
              <span>XL</span>
            </td>
            <td>
              <span>96</span>
            </td>
            <td>
              <span>80</span>
            </td>
            <td>
              <span>103</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>44</span>
            </td>
            <td>
              <span>XXL</span>
            </td>
            <td>
              <span>100</span>
            </td>
            <td>
              <span>85</span>
            </td>
            <td>
              <span>106</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>46</span>
            </td>
            <td>
              <span>3XL</span>
            </td>
            <td>
              <span>104</span>
            </td>
            <td>
              <span>90</span>
            </td>
            <td>
              <span>109</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>48</span>
            </td>
            <td>
              <span>4XL</span>
            </td>
            <td>
              <span>110</span>
            </td>
            <td>
              <span>96.5</span>
            </td>
            <td>
              <span>114</span>
            </td>
          </tr>
        </tbody>
      </table>
    </section>
  );
};

export default SizeGuide;
