import { useLanguage } from '../features/language/useLanguage';

const ConvertingGuide = () => {
  const { language } = useLanguage();
  return (
    <section>
      <h2>{language.sizeGuide} </h2>
      <p>{language.sizeGuideInfo}</p>
      <table>
        <caption>
          <span>{language.convertingSize}</span>
        </caption>
        <thead>
          <tr>
            <th scope="col">
              <span>EU</span>
            </th>
            <th scope="col">
              <span>INT</span>
            </th>
            <th scope="col">
              <span>FR</span>
            </th>
            <th scope="col">
              <span>IT</span>
            </th>
            <th scope="col">
              <span>UK</span>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>32</span>
            </td>
            <td>
              <span>XXS</span>
            </td>
            <td>
              <span>34</span>
            </td>
            <td>
              <span>38</span>
            </td>
            <td>
              <span>4</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>34</span>
            </td>
            <td>
              <span>XS</span>
            </td>
            <td>
              <span>36</span>
            </td>
            <td>
              <span>40</span>
            </td>
            <td>
              <span>6</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>36</span>
            </td>
            <td>
              <span>S</span>
            </td>
            <td>
              <span>38</span>
            </td>
            <td>
              <span>42</span>
            </td>
            <td>
              <span>8</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>38</span>
            </td>
            <td>
              <span>M</span>
            </td>
            <td>
              <span>40</span>
            </td>
            <td>
              <span>44</span>
            </td>
            <td>
              <span>10</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>40</span>
            </td>
            <td>
              <span>L</span>
            </td>
            <td>
              <span>42</span>
            </td>
            <td>
              <span>46</span>
            </td>
            <td>
              <span>12</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>42</span>
            </td>
            <td>
              <span>XL</span>
            </td>
            <td>
              <span>44</span>
            </td>
            <td>
              <span>48</span>
            </td>
            <td>
              <span>14</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>44</span>
            </td>
            <td>
              <span>XXL</span>
            </td>
            <td>
              <span>46</span>
            </td>
            <td>
              <span>50</span>
            </td>
            <td>
              <span>16</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>46</span>
            </td>
            <td>
              <span>3XL</span>
            </td>
            <td>
              <span>48</span>
            </td>
            <td>
              <span>52</span>
            </td>
            <td>
              <span>18</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>48</span>
            </td>
            <td>
              <span>4XL</span>
            </td>
            <td>
              <span>50</span>
            </td>
            <td>
              <span>54</span>
            </td>
            <td>
              <span>20</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>50</span>
            </td>
            <td>
              <span>5XL</span>
            </td>
            <td>
              <span>52</span>
            </td>
            <td>
              <span>56</span>
            </td>
            <td>
              <span>22</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>52</span>
            </td>
            <td>
              <span>6XL</span>
            </td>
            <td>
              <span>54</span>
            </td>
            <td>
              <span>58</span>
            </td>
            <td>
              <span>24</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>54</span>
            </td>
            <td>
              <span>7XL</span>
            </td>
            <td>
              <span>56</span>
            </td>
            <td>
              <span>60</span>
            </td>
            <td>
              <span>26</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>56</span>
            </td>
            <td>
              <span>8XL</span>
            </td>
            <td>
              <span>58</span>
            </td>
            <td>
              <span>62</span>
            </td>
            <td>
              <span>28</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>58</span>
            </td>
            <td>
              <span>9XL</span>
            </td>
            <td>
              <span>60</span>
            </td>
            <td>
              <span>64</span>
            </td>
            <td>
              <span>30</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>60</span>
            </td>
            <td>
              <span>10XL</span>
            </td>
            <td>
              <span>62</span>
            </td>
            <td>
              <span>66</span>
            </td>
            <td>
              <span>32</span>
            </td>
          </tr>
        </tbody>
      </table>
    </section>
  );
};

export default ConvertingGuide;
