import { useLanguage } from '../features/language/useLanguage';

const SizeGuide = () => {
  const { language } = useLanguage();
  return (
    <section>
      <h2>{language.sizeGuide} </h2>
      <p>{language.sizeGuideInfo}</p>
      <p>{language.convertingSize}</p>
      <table>
        <caption>
          <span>{language.bodyMeasurements}</span>
        </caption>
        <thead>
          <tr>
            <th scope="col">
              <span>EU</span>
            </th>
            <th scope="col">
              <span>INT</span>
            </th>
            <th scope="col">
              <span>{language.chest}</span>
            </th>
            <th scope="col">
              <span>{language.waist}</span>
            </th>
            <th scope="col">
              <span>{language.hips}</span>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>32</span>
            </td>
            <td>
              <span>XXS</span>
            </td>
            <td>
              <span>76</span>
            </td>
            <td>
              <span>63</span>
            </td>
            <td>
              <span>85</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>34</span>
            </td>
            <td>
              <span>XS</span>
            </td>
            <td>
              <span>80</span>
            </td>
            <td>
              <span>66</span>
            </td>
            <td>
              <span>89</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>36</span>
            </td>
            <td>
              <span>S</span>
            </td>
            <td>
              <span>84</span>
            </td>
            <td>
              <span>69</span>
            </td>
            <td>
              <span>93</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>38</span>
            </td>
            <td>
              <span>M</span>
            </td>
            <td>
              <span>88</span>
            </td>
            <td>
              <span>72</span>
            </td>
            <td>
              <span>97</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>40</span>
            </td>
            <td>
              <span>L</span>
            </td>
            <td>
              <span>92</span>
            </td>
            <td>
              <span>76</span>
            </td>
            <td>
              <span>100</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>42</span>
            </td>
            <td>
              <span>XL</span>
            </td>
            <td>
              <span>96</span>
            </td>
            <td>
              <span>80</span>
            </td>
            <td>
              <span>103</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>44</span>
            </td>
            <td>
              <span>XXL</span>
            </td>
            <td>
              <span>100</span>
            </td>
            <td>
              <span>85</span>
            </td>
            <td>
              <span>106</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>46</span>
            </td>
            <td>
              <span>3XL</span>
            </td>
            <td>
              <span>104</span>
            </td>
            <td>
              <span>90</span>
            </td>
            <td>
              <span>109</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>48</span>
            </td>
            <td>
              <span>4XL</span>
            </td>
            <td>
              <span>110</span>
            </td>
            <td>
              <span>96.5</span>
            </td>
            <td>
              <span>114</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>50</span>
            </td>
            <td>
              <span>5XL</span>
            </td>
            <td>
              <span>116</span>
            </td>
            <td>
              <span>103</span>
            </td>
            <td>
              <span>119</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>52</span>
            </td>
            <td>
              <span>6XL</span>
            </td>
            <td>
              <span>122</span>
            </td>
            <td>
              <span>109.5</span>
            </td>
            <td>
              <span>124</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>54</span>
            </td>
            <td>
              <span>7XL</span>
            </td>
            <td>
              <span>128</span>
            </td>
            <td>
              <span>116</span>
            </td>
            <td>
              <span>130</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>56</span>
            </td>
            <td>
              <span>8XL</span>
            </td>
            <td>
              <span>134</span>
            </td>
            <td>
              <span>122.5</span>
            </td>
            <td>
              <span>136</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>58</span>
            </td>
            <td>
              <span>9XL</span>
            </td>
            <td>
              <span>140</span>
            </td>
            <td>
              <span>129</span>
            </td>
            <td>
              <span>142</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>60</span>
            </td>
            <td>
              <span>10XL</span>
            </td>
            <td>
              <span>146</span>
            </td>
            <td>
              <span>135.5</span>
            </td>
            <td>
              <span>148</span>
            </td>
          </tr>
        </tbody>
      </table>
    </section>
  );
};

export default SizeGuide;
