export enum MainPath {
  About = 'about',
  Admin = 'admin',
  AdminCategories = 'categories',
  AdminCategoryCreate = 'category/create',
  AdminCategoryUpdate = 'category/update',
  AdminOrders = 'orders',
  AdminProducts = 'products',
  AdminProfile = 'profile',
  AdminSubCategories = 'sub-categories',
  AdminSubCategoryCreate = 'sub-category/create',
  AdminSubCategoryUpdate = 'sub-category/update',
  AdminSubCategoryView = 'sub-category/view',
  Collection = 'collection',
  Contact = 'contact',
  Home = 'home',
  Login = 'login',
  MyAccount = 'myAccount',
  Orders = 'myOrders',
  Root = '/',
  ShoppingCart = 'shopping-cart',
  Signup = 'signup',
  Update = 'update',
  Users = 'users',
}

export enum LinkText {
  About = 'about',
  Account = 'account',
  Categories = 'categories',
  Collection = 'collection',
  Contact = 'contact',
  Home = 'home',
  Login = 'login',
  MyAccount = 'myAccount',
  Orders = 'orders',
  Products = 'products',
  Profile = 'profile',
  Signup = 'signup',
  SubCategories = 'subCategories',
  Update = 'update',
  Users = 'users',
}
