enum AdminPath {
  About = 'about',
  Admin = 'admin',
  AdminCategories = '/admin/categories',
  AdminCategoryCreate = '/admin/categories/create',
  AdminCategoryUpdate = '/admin/categories/update',
  AdminOrders = '/admin/orders',
  AdminProductCreate = '/admin/products/create',
  AdminProducts = '/admin/products',
  AdminProductUpdate = '/admin/products/update',
  AdminProductView = '/admin/products/view',
  AdminProfile = 'profile',
  AdminSubCategories = '/admin/sub-categories',
  AdminSubCategoryCreate = '/admin/sub-categories/create',
  AdminSubCategoryUpdate = '/admin/sub-categories/update',
  AdminSubCategoryView = '/admin/sub-categories/view',
  AdminUserCreate = '/admin/users/create',
}

enum ShopPath {
  Collection = 'collection',
  Contact = 'contact',
  Favorites = '/favorites',
  Home = 'home',
  Kids = '/collection/kids',
  Login = 'login',
  Men = '/collection/men',
  MyAccount = 'myAccount',
  MyOrders = 'myOrders',
  Root = '/',
  ShoppingCart = 'shopping-cart',
  Signup = 'signup',
  Users = '/admin/users',
  Women = '/collection/women',
}

enum LinkText {
  About = 'about',
  Account = 'account',
  Categories = 'categories',
  Collection = 'collection',
  Contact = 'contact',
  Create = 'create',
  CreateNewCategory = 'createNewCategory',
  CreateNewProduct = 'createNewProduct',
  CreateNewUser = 'createNewUser',
  Dashboard = 'dashboard',
  Edit = 'edit',
  Favorites = 'favorites',
  Home = 'home',
  Kids = 'kids',
  Login = 'login',
  Men = 'men',
  MyAccount = 'myAccount',
  Orders = 'orders',
  Products = 'products',
  Profile = 'profile',
  Signup = 'signup',
  SubCategories = 'subCategories',
  Update = 'update',
  Users = 'users',
  View = 'view',
  Women = 'women',
}

export { AdminPath, LinkText, ShopPath };
