enum AdminPath {
  Admin = 'admin',
  AdminCategories = '/admin/categories',
  AdminCategoryCreate = '/admin/categories/create',
  AdminCategoryUpdate = '/admin/categories/update',
  AdminOrders = '/admin/orders',
  AdminProductCreate = '/admin/products/create',
  AdminProducts = '/admin/products',
  AdminProductUpdate = '/admin/products/update',
  AdminProductView = '/admin/products/view',
  AdminProfile = 'profile',
  AdminSubCategories = '/admin/subCategories',
  AdminSubCategoryCreate = '/admin/subCategories/create',
  AdminSubCategoryUpdate = '/admin/subCategories/update',
  AdminSubCategoryView = '/admin/subCategories/view',
  AdminUserCreate = '/admin/users/create',
}

enum ShopPath {
  Collection = 'collection',
  CollectionCategory = 'collection/:category',
  CollectionCategoryId = 'collection/:category/:categoryId',
  CollectionSingleProduct = 'collection/:category/:categoryId/:id',
  Contact = 'contact',
  CreateAccount = 'createAccount',
  Favorites = '/favorites',
  Home = 'home',
  Kids = '/collection/kids',
  Login = 'login',
  Men = '/collection/men',
  MyAccount = 'myAccount',
  MyOrders = 'myOrders',
  Product = 'product',
  Profile = 'profile',
  Root = '/',
  ShoppingCart = 'shopping-cart',
  Users = '/admin/users',
  Women = '/collection/women',
}

enum LinkText {
  Account = 'account',
  Categories = 'categories',
  Collection = 'collection',
  Contact = 'contact',
  Create = 'create',
  CreateAccount = 'createAccount',
  CreateNewCategory = 'createNewCategory',
  CreateNewProduct = 'createNewProduct',
  CreateNewUser = 'createNewUser',
  Dashboard = 'dashboard',
  Edit = 'edit',
  Favorites = 'favorites',
  Home = 'home',
  Kids = 'kids',
  Login = 'login',
  Men = 'men',
  MyAccount = 'myAccount',
  Orders = 'orders',
  Products = 'products',
  Profile = 'profile',
  SubCategories = 'subCategories',
  Update = 'update',
  Users = 'users',
  View = 'view',
  Women = 'women',
}

export { AdminPath, LinkText, ShopPath };
